-- Aula10Homework03

SELECT *

FROM            PESSOA        P
RIGHT OUTER JOIN   CONTATO C  ON (P.ID_PESSOA =  C.ID_PESSOA)


SELECT *

FROM PESSOA P
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO PX ON (P.ID_PESSOA = PX.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA EP ON (PX.ID_ENDERECO = EP.ID_ENDERECO)



SELECT *
FROM PESSOA P
RIGHT OUTER JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO PX ON (P.ID_PESSOA = PX.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA EP ON (PX.ID_ENDERECO = EP.ID_ENDERECO)



SELECT *

FROM            PESSOA        P
FULL OUTER JOIN   CONTATO C  ON (P.ID_PESSOA =  C.ID_PESSOA)



SELECT *

FROM PESSOA P
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO PX ON (P.ID_PESSOA = PX.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA EP ON (PX.ID_ENDERECO = EP.ID_ENDERECO)



SELECT *
FROM PESSOA P
FULL OUTER JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO PX ON (P.ID_PESSOA = PX.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA EP ON (PX.ID_ENDERECO = EP.ID_ENDERECO)




SELECT *
FROM PESSOA P
WHERE EXISTS (SELECT *
				FROM PESSOA_X_PESSOA_ENDERECO PX
				WHERE P.ID_PESSOA = PX.ID_PESSOA)
				
				

							
SELECT NOME, ID_PESSOA 
FROM PESSOA P 
UNION
SELECT LOGRADOURO, ID_ENDERECO
FROM ENDERECO_PESSOA EP
				